name: 'formatting'
description: 'CI formatting check'
inputs:
  path-to-repo:
    description: 'Path to repository folder'
    required: false
    default: ./
runs:
  using: "composite"
  steps: 
      - name: Install Uncrustify
        run: sudo apt-get install uncrustify
      - name: Run Uncrustify
        run: find . -iname "*.[hc]" -exec uncrustify --check -c tools/uncrustify.cfg {} +
      - name: Check For Trailing Whitespace
        run: |
          set +e
          grep --exclude="README.md" -rnI -e "[[:blank:]]$" .
          if [ "$?" = "0" ]; then
            echo "Files have trailing whitespace."
            exit 1
          else
            exit 0
          fi
      - name: Check for CRLF
        run: |
          set +e
          find . -path ./.git -prune -o -exec file {} + |  grep "CRLF"
          if [ "$?" = "0" ]; then
            echo "Files have CRLF line endings."
            exit 1
          else
            exit 0
          fi