name: 'formatting'
description: 'CI formatting check'
inputs:
  path:
    description: 'Path to repository folder to run formatting check for. '
    required: false
    default: ./
  exclude-files:
    description: 'List of comma-separated files to exclude from the formatting check. Eg file1,file2'
    required: false
    default: ''
  exclude-dirs:
    description: 'List of comma-separated directories to exclude from the formatting check. Eg docs,build'
    required: false
    default: ''
  include-extensions:
    description: 'List of comma-separated extensions to add to the formatting check . Eg md,dox'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
      - env:
          # At time of writing, you can't add a global environment
          # to an action file so stuck with this. If this gets changed
          # Please move this
          bashPass: \033[32;1mPASSED -
          bashInfo: \033[33;1mINFO -
          bashFail: \033[31;1mFAILED -
          bashEnd:  \033[0m
          stepName: Install Clang Format
        name: ${{ env.stepName }}
        shell: bash
        run: |
          # ${{ env.stepName }}
          echo "::group::${{ env.stepName }}"
          sudo apt-get install clang-format fd-find
          echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
          export PATH="$PATH:$GITHUB_ACTION_PATH"

          fdfind --version
          fdInstalled=$?

          clang-format --version
          clangFormatInstalled=$?

          getFiles --help
          getFilesAdded=$?

          echo "::endgroup::"
<<<<<<< HEAD
          : # Run a git diff to print the differences if any exist, return an error code if there are any
          git diff -G. --exit-code
          if [ "$?" = "0" ]; then
            echo -e "\033[32;3mUncrustify check passed\033[0m"
            exit 0
=======
          if [ $getFilesAdded -eq 1 ] || [ $clangFormatInstalled -eq 1 ] || [ $fdInstalled -eq 1 ]; then
            echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
            exit 1
          else
            echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
            exit 0
          fi

      - env:
          stepName: Validate Inputs
          bashPass:   \033[32;1mPASSED -
          bashInfo:   \033[33;1mINFO -
          bashFail:   \033[31;1mFAILED -
          bashEnd:    \033[0m
        name: ${{ env.stepName }}
        id: validate-inputs
        shell: bash
        run: |
          # ${{ env.stepName }}
          # Check exclude dirs for possible input issues
          if [[ "${{ inputs.exclude-dirs }}" = *"\n"* ]]; then
            echo -e "${{ env.bashFail }} YOU HAVE NEWLINE IN YOUR EXCLUDE-DIRS. ${{ env.bashEnd }}"
            exitStatus=1
          fi

      - env:
          bashPass: \033[32;1mPASSED -
          bashInfo: \033[33;1mINFO -
          bashFail: \033[31;1mFAILED -
          bashEnd:  \033[0m
          stepName: Run Clang Format
        name: ${{ env.stepName }}
        if: ${{ steps.validate-inputs.outcome}} = "success"
        working-directory: ${{ inputs.path }}
        shell: bash
        run: |
          # ${{ env.stepName }}
          echo -e "${{ env.bashInfo }} Using clang-format version "$(clang-format --version)" ${{ env.bashEnd }}"
          echo "::group::${{ env.stepName }}"
          exitCode=0
          export PATH="$PATH:$GITHUB_ACTION_PATH"
          files=$(getFiles --exclude-files="${{inputs.exclude-files}}" --exclude-dir="${{inputs.exclude-dirs}}" )
          if ! [ $? -eq 0 ]; then
              echo -e "${{ env.bashFail }} Error calling getFiles() ${{ env.bashEnd }}"
              echo -e "$fileOut"
              exit 1
          fi

          # Loop over the files that matched the above conditions
          for file in ${files[@]}; do

            # set +e so we don't exit on the first file with an error
            # Doing it here instead of over the whole loop incase there
            # Is an error that gets raised in the loop (somehow)
            set +e

            # Pipe the output of the command to a variable
            # This way we can print the command only if it fails
            fileOut=$(clang-format -i --verbose --style=file $file)

            # Re-enable failing or error
            set -e

          done

          echo "::endgroup::"
          # Run a git diff to print the differences if any exist, return an error code if there are any

          echo "::group::File Difference"
          set +e
          git diff --exit-code
          exitCode=$?
          set -e
          echo "::endgroup::"

          if [ $exitCode -eq 0 ]; then
            echo -e "${{ env.bashPass }} ${{ env.stepName }} ${{ env.bashEnd }}"
>>>>>>> 11571d313a969fd0f8c294f532cb0a8b2feb1f97
          else
            echo -e "${{ env.bashFail }} List of files with formatting errors: ${{ env.bashEnd }}"
            echo -e "${{ env.bashFail }} "$(git diff --name-only)" ${{ env.bashEnd }} "
            echo -e "${{ env.bashFail }} ${{ env.stepName }} ${{ env.bashEnd }}"
          fi
<<<<<<< HEAD
        shell: bash
      - name: Check For Trailing Whitespace
        working-directory: ${{ inputs.path }}
        run: |
          : # Trailing Whitespace Check
          set +e
          grep --exclude={README.md,${{ inputs.exclude-files }}} --exclude-dir={${{ inputs.exclude-dirs }},'.git'} -rnI -e "[[:blank:]]$" .
          if [ "$?" = "0" ]; then
            set -e
            echo -e "\033[32;31mFiles have trailing whitespace.\033[0m"
            exit 1
          else
            echo -e "\033[32;3mTrailing whitespace check passed\033[0m"
            exit 0
          fi
        shell: bash
      - name: Check for CRLF
        working-directory: ${{ inputs.path }}
        run: |
          : # Check for CRLF Line Ending
          set +e
          find . -path ./.git -prune -o -exec file {} + |  grep "CRLF"
          if [ "$?" = "0" ]; then
            set -e
            echo -e "\033[32;31mFiles have CRLF line endings.\033[0m"
            exit 1
          else
            echo -e "\033[32;3mLine ending check passed\033[0m"
            exit 0
          fi
        shell: bash
      - name: Set file permissions
        working-directory: ${{ inputs.path }}
        run: |
          : # .c and .h file execute permissions check
          set +e
          find . -type f \( -name "*.h" -o -name "*.c" \) -exec chmod -x {} +
          find . -type f \( -name "*.py" -o -name "*.sh" \) -exec chmod +x {} +
          # how do we change file perms without having to create a CR? or create and auto-accept one, for that matter

          if [ "$?" = "0" ]; then
            echo -e "\033[32;3mFile perms changed successfully\033[0m"
            exit 0
          else
            set -e
            echo -e "\033[32;31mFile perms could not be changed successfully\033[0m"
            exit 1
          fi
        shell: bash
=======
          exit $exitCode
>>>>>>> 11571d313a969fd0f8c294f532cb0a8b2feb1f97
