name: 'formatting'
description: 'CI formatting check'
inputs:
  repo-to-clone:
    description: 'Repository to clone for formatting check (Eg. FreeRTOS/coreMQTT)'
    required: true
  branch:
    description: 'Branch of repository to use (Eg. main)'
    required: true
    default: main
runs:
  using: "composite"
  steps: 
      - uses: actions/checkout@v2
        with:
          repository: ${{ inputs.repo-to-clone }}
          ref: ${{ inputs.branch }}
      - name: Install Uncrustify
        run: sudo apt-get install uncrustify
      - name: Run Uncrustify
        run: find . -iname "*.[hc]" -exec uncrustify --check -c tools/uncrustify.cfg {} +
      - name: Check For Trailing Whitespace
        run: |
          set +e
          grep --exclude="README.md" -rnI -e "[[:blank:]]$" .
          if [ "$?" = "0" ]; then
            echo "Files have trailing whitespace."
            exit 1
          else
            exit 0
          fi
      - name: Check for CRLF
        run: |
          set +e
          find . -path ./.git -prune -o -exec file {} + |  grep "CRLF"
          if [ "$?" = "0" ]; then
            echo "Files have CRLF line endings."
            exit 1
          else
            exit 0
          fi