name: 'complexity'
description: 'CI complexity check'
inputs:
  path:
    description: 'Path to repository folder to run complexity check in.'
    required: false
    default: ./
  source_path:
    description: 'Path to the folder in the repository containing the source code.'
    required: false
    default: source
  horrid_threshold:
    description: 'The horrid threshold parameter passed to the invocation of complexity'
    required: false
    default: 16

runs:
  using: "composite"
  steps:

      - env:
          stepName: Install Dependencies
          bashPass: \033[32;1mPASSED -
          bashInfo: \033[33;1mINFO -
          bashFail: \033[31;1mFAILED -
          bashEnd:  \033[0
        name: ${{ env.stepName }}
        shell: bash
        run: |
          # ${{ env.stepName }}
          echo "::group::${{ env.stepName }}"
          sudo apt-get install complexity fd-find -y
          echo "::endgroup::"
          echo -e "${{ env.bashPass }} ${{env.stepName }} ${{ env.bashEnd }}"

      - env:
          stepName: Complexity
          bashPass: \033[32;1mPASSED -
          bashInfo: \033[33;1mINFO -
          bashFail: \033[31;1mFAILED -
          bashEnd:  \033[0m
        working-directory: ${{ inputs.path }}
        shell: bash
        run: |
          # ${{ env.stepName }}
          echo "::group::${{ env.stepName }}"
          echo -e "${{ env.bashInfo }} Have complexity limit of ${{ inputs.horrid_threshold }} ${{ env.bashEnd }}"

          # Use fdfind to find all files ending with a .c inside of the input directory
          # From there run the complexity check against them
          fdfind . -e c ${{ inputs.source_path }} --exec \
            complexity --scores --threshold=0 --horrid-threshold=${{ inputs.horrid_threshold }}

          echo "::endgroup::"
          echo -e "${{ env.bashPass }} ${{env.stepName }} ${{ env.bashEnd }}"
