name: Test actions

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  # The bash escape character is \033
  bashPass:   \033[32;1mPASSED -
  bashInfo:   \033[33;1mINFO -
  bashFail:   \033[31;1mFAILED -
  bashEnd:    \033[0m

jobs:

  test-complexity-check:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: skptak/coreMQTT
          ref: main
          path: coreMQTT

      - name: Test complexity check action
        uses: ./complexity
        continue-on-error: true
        with:
          path: coreMQTT
          # The default threshold for all repos is 16
          horrid_threshold: 16

  test-doxygen-zip-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3

      - uses: actions/checkout@v3
        with:
          repository: aws/aws-iot-device-sdk-embedded-C
          submodules: recursive
          ref: main
          path: aws-iot-device-sdk-embedded-C

      - name: Test doxygen build action
        uses: ./doxygen
        with:
          path: ./aws-iot-device-sdk-embedded-C
          libs_parent_dir_path: libraries/standard,libraries/aws
          generate_zip: true

  test-doxygen-non-zip-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: skptak/coreMQTT
          ref: main
          path: coreMQTT

      - name: Test doxygen build action
        uses: ./doxygen
        with:
          path: coreMQTT

  test-spell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: skptak/coreMQTT
          ref: main
          path: coreMQTT

      - name: Test spell check action
        uses: ./spellings
        with:
          path: coreMQTT

  test-rust-spell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: skptak/coreMQTT
          ref: main
          path: coreMQTT

      - name: Test spell check action
        uses: ./rust-spell-check
        with:
          path: coreMQTT

  test-rust-spell-checker-needs-to-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: skptak/coreMQTT
          ref: main
          path: coreMQTT

      - name: Delete the pre-built spell-checker
        shell: bash
        run: file=$(find . -name spell-checker); readlink -f "$file" ; rm "$file"

      - name: Test Spell Check Build and Run
        uses: ./rust-spell-check
        with:
          path: coreMQTT

  test-rust-spell-checker-find-mistake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: skptak/coreMQTT
          ref: main
          path: coreMQTT

      - name: Empty the lexicon
        shell: bash
        working-directory: coreMQTT
        run: file=$(find . -name .cSpellWords.txt); readlink -f "$file" ; > "$file"

      - name: Test Spell Check Fails on Misspelled Word
        id: test-spell-check-find-mistake
        continue-on-error: true
        uses: ./rust-spell-check
        with:
          path: coreMQTT

      - env:
          stepName: Check Failure Test Case
        name: ${{ env.stepName }}
        id: check-failure-test-cases
        shell: bash
        run: |
          # ${{ env.stepName }}
          exitStatus=0
          if [ "${{ steps.test-spell-check-find-mistake.outcome}}" = "failure" ]; then
            echo -e "${{ env.bashPass }} Functional | Failure | Fail on Misspelled Word | Had Expected "failure" ${{ env.bashEnd }}"
          else
            echo -e "${{ env.bashFail }} Functional | Failure | Fail on Misspelled Word | Had Unexpected "success" ${{ env.bashEnd }}"
            exitStatus=1
          fi

  test-coverage-cop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: skptak/coreMQTT
          ref: main
          path: coreMQTT

      - name: Build
        run: |
          sudo apt-get install -y lcov
          cmake -S ./coreMQTT/test -B build/ \
          -G "Unix Makefiles" \
          -DCMAKE_BUILD_TYPE=Debug \
          -DBUILD_CLONE_SUBMODULES=ON \
          -DCMAKE_C_FLAGS='--coverage -Wall -Wextra -Werror -DNDEBUG -DLIBRARY_LOG_LEVEL=LOG_DEBUG'
          make -C build/ all

      - name: Test
        run: |
          cd build/
          ctest -E system --output-on-failure
          cd ..

      - name: Run Coverage
        run: |
          make -C build/ coverage
          declare -a EXCLUDE=("\*test/\*" "\*CMakeCCompilerId\*" "\*mocks\*")
          echo ${EXCLUDE[@]} | xargs lcov --rc lcov_branch_coverage=1 -r build/coverage.info -o build/coverage.info
          lcov --rc lcov_branch_coverage=1 --list build/coverage.info

      - name: Test coverage cop action
        uses: ./coverage-cop
        with:
          path: ./build/coverage.info
          branch-coverage-min: 70
          line-coverage-min: 100

  test-memory-statistics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test memory statistics action
        uses: ./memory_statistics
        with:
          path: memory_statistics/test
          config: ./memory_statistics_config.json
          output: ./size_table_new.html
          check_against: ./size_table_expected.html

  test-link-verifier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup python environment
        uses: actions/setup-python@v3

      - name: Test link verifier action
        uses: ./link-verifier
        with:
          path: ./
          exclude-dirs: complexity,formatting
          include-file-types: .c,.html

  test-manifest-verifier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup python environment
        uses: actions/setup-python@v3

      - name: Checkout the FreeRTOS/FreeRTOS repository for testing action on.
        uses: actions/checkout@v3
        with:
          repository: FreeRTOS/FreeRTOS
          ref: '202107.00'
          path: FreeRTOS
          submodules: recursive

      - name: Test manifest verifier
        uses: ./manifest-verifier
        with:
          path: ./FreeRTOS
          exclude-submodules: FreeRTOS-Plus/Test/CMock,FreeRTOS/Test/CMock/CMock,FreeRTOS/Test/litani
          fail-on-incorrect-version: true
